services:

  spark-master:
    image: spark:4.0.1-java21-python3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports: [ 7077:7077, 8000:8080 ]
    networks:
      - crypto-analyzer

  spark-worker-1:
    image: spark:4.0.1-java21-python3
    container_name: spark-worker-1
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - crypto-analyzer

  spark-worker-2:
    image: spark:4.0.1-java21-python3
    container_name: spark-worker-2
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    networks:
      - crypto-analyzer

networks:
  crypto-analyzer:
    name: crypto-analyzer
    external: true
